name: Data Source

on:
  push:
    branches: master
  schedule:
    - cron: '0 16 * * *'

jobs:
  api-test:
    runs-on: ubuntu-latest
    if: github.repository == 'gautemo/covid19-timeline'

    steps:
    - name: Fetch URL
      uses: boyeborg/fetch-url-action@v1.1
      with:
        url: 'https://europe-west1-covid-19-map-spread.cloudfunctions.net/getCovidData'
    - name: Fetch API Data
      uses: JamesIves/fetch-api-data-action@1.0.4
      with:
        ENDPOINT: 'https://europe-west1-covid-19-map-spread.cloudfunctions.net/getCovidData'
        SAVE_LOCATION: 'cloud-functions'
        SAVE_NAME: 'backupData'
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
        git status
