name: Data Source

on:
  push:
    branches: master
  schedule:
    - cron: '0 16 * * *'

jobs:
  api-test:
    runs-on: ubuntu-latest
    if: github.repository == 'gautemo/covid19-timeline'

    steps:
    - name: Fetch URL
      uses: boyeborg/fetch-url-action@v1.1
      with:
        url: 'https://europe-west1-covid-19-map-spread.cloudfunctions.net/getCovidData'
    - name: Fetch API Data
      uses: JamesIves/fetch-api-data-action@1.0.4
      with:
        ENDPOINT: 'https://europe-west1-covid-19-map-spread.cloudfunctions.net/getCovidData'
        SAVE_LOCATION: 'cloud-functions'
        SAVE_NAME: 'backupData'
    - uses: actions/checkout@v2
      env: 
        FETCH_API_DATA: empty
    - name: Commit file to repo
      run: |
        git status
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "GitHub Action, daily backup of API data" -a
        git push https://gautemo:${{ secrets.MY_GITHUB_TOKEN }}@github.com/gautemo/covid19-timeline.git
#    - name: GitHub Push
#      uses: ad-m/github-push-action@v0.5.0
#      with:
#        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
